<p><strong><?php echo $this->getMethod()->getTitle() ?></strong></p>

<?php if($this->getOrder()->getAdditionalInformation('payment_id') != ""): ?>
    <p><?php echo $this->__('Numero de Pagamento (MercadoPago): %s', $this->htmlEscape($this->getOrder()->getAdditionalInformation('payment_id'))); ?></p>
<?php endif; ?>
    
<?php if($this->getOrder()->getAdditionalInformation('status') != ""): ?>
    <p><?php echo $this->__('Status de Pagamento: %s (%s)', $this->htmlEscape($this->getOrder()->getAdditionalInformation('status')), $this->htmlEscape($this->getOrder()->getAdditionalInformation('status_detail'))); ?></p>
<?php endif; ?>

<p>Clique no link para gerar o boleto.</p>
<a href="<?php echo urldecode($this->htmlEscape($this->getOrder()->getAdditionalInformation('activation_uri'))); ?>" target="_blank">Gerar Boleto</a>

