<p><strong><?php echo $this->getMethod()->getTitle() ?></strong></p>

<?php if(Mage::app()->getRequest()->getRouteName()=="sales"): ?>
    
        
    <?php if($this->getOrder()->getAdditionalInformation('cardholderName') != ""): ?>
        <p><?php echo $this->__('Card Holder Name: %s', $this->htmlEscape($this->getOrder()->getAdditionalInformation('cardholderName'))); ?></p>
    <?php endif; ?>
    
    <?php if($this->getOrder()->getAdditionalInformation('trunc_card') != ""): ?>
        <p><?php echo $this->__('Card Number: %s', $this->htmlEscape($this->getOrder()->getAdditionalInformation('trunc_card'))); ?></p>
    <?php endif; ?>
    
    <?php if($this->getOrder()->getAdditionalInformation('payment_method') != ""): ?>
        <p><?php echo $this->__('Payment Method: %s', $this->htmlEscape($this->getOrder()->getAdditionalInformation('payment_method'))); ?></p>
    <?php endif; ?>
    
    <?php if($this->getOrder()->getAdditionalInformation('installments') != ""): ?>
        <p><?php echo $this->__('Installments: %s', $this->htmlEscape($this->getOrder()->getAdditionalInformation('installments'))); ?></p>
    <?php endif; ?>
    
    <?php if($this->getOrder()->getAdditionalInformation('statement_descriptor') != ""): ?>
        <p><?php echo $this->__('Statement Descriptor: %s', $this->htmlEscape($this->getOrder()->getAdditionalInformation('statement_descriptor'))); ?></p>
    <?php endif; ?>
    
    <?php if($this->getOrder()->getAdditionalInformation('payment_id') != ""): ?>
        <p><?php echo $this->__('Payment Id (MercadoPago): %s', $this->htmlEscape($this->getOrder()->getAdditionalInformation('payment_id'))); ?></p>
    <?php endif; ?>
    
    <?php if($this->getOrder()->getAdditionalInformation('status') != ""): ?>
        <p><?php echo $this->__('Payment Status: %s', $this->htmlEscape($this->getOrder()->getAdditionalInformation('status'))); ?></p>
    <?php endif; ?>
    
    <?php if($this->getOrder()->getAdditionalInformation('status_detail') != ""): ?>
        <p><?php echo $this->__('Payment Status Detail: %s', $this->htmlEscape($this->getOrder()->getAdditionalInformation('status_detail'))); ?></p>
    <?php endif; ?>

    
    
<?php endif;?>
