<p><strong><?php echo $this->getMethod()->getTitle() ?></strong></p>

<?php if($this->getOrder()->getAdditionalInformation('payment_id') != ""): ?>
    <p><?php echo $this->__('Payment Id (MercadoPago): %s', $this->htmlEscape($this->getOrder()->getAdditionalInformation('payment_id'))); ?></p>
<?php endif; ?>
    
<?php if($this->getOrder()->getAdditionalInformation('status') != ""): ?>
    <p><?php echo $this->__('Payment Status: %s (%s)', $this->htmlEscape($this->getOrder()->getAdditionalInformation('status')), $this->htmlEscape($this->getOrder()->getAdditionalInformation('status_detail'))); ?></p>
<?php endif; ?>

<p><?php echo $this->__('Click on the link to generate the ticket'); ?>.</p>
<a href="<?php echo urldecode($this->htmlEscape($this->getOrder()->getAdditionalInformation('activation_uri'))); ?>" target="_blank">
    <?php echo $this->__('Generate Ticket'); ?>
</a>

