<?php
/**
 * @class MercadoPago_MercadoEnvios_Block_Adminhtml_System_Config_Fieldset_Mapping
 */
$_htmlId = $this->getHtmlId() ? $this->getHtmlId() : '_' . uniqid();
$productCode = $this->_getAttributes();
$sizeUnit = array('cm', 'mt');
$weightUnit = array('kg', 'gr');
$meCode = array('length','width','height', 'weight');
$meLabel = $this->_getMeLabel();
$prevValues = array();
$unit = $sizeUnit;

$prevValues = $this->_getStoredMappingValues();

?>

<div class="grid" id="grid<?php echo $_htmlId ?>">
    <table cellpadding="0" cellspacing="0" class="border">
        <tr class="headings" id="headings<?php echo $_htmlId ?>">
            <th><?php echo $this->__('MercadoEnvios')?></th>
            <th><?php echo $this->__('Product Attribute')?></th>
            <th><?php echo $this->__('Product Attribute Unit')?></th>
        </tr>
        <?php foreach($meCode as $key => $meOption):?>
            <tr id="<?php echo $meOption ?>">
                    <td>
                        <label><?php echo $meLabel[$key] ?>:</label>
                    </td>
                    <td>
                        <select name="groups[mercadoenvios][fields][attributesmapping][value][<?php echo $meOption ?>][attribute_code]">
                            <?php foreach($productCode as $option):?>
                                <option value="<?php echo $option->getAttributeCode() ?>"
                                    <?php echo ( isset($prevValues[$meOption]['attribute_code']) && $prevValues[$meOption]['attribute_code'] == $option->getAttributeCode()) ? "selected='selected'" : "" ?>><?php echo $option->getFrontendLabel() ?>
                                </option>
                            <?php endforeach; ?>
                        </select>
                    </td>
                    <?php if ($meOption == 'weight') : $unit = $weightUnit; endif;?>
                    <td>
                        <select name="groups[mercadoenvios][fields][attributesmapping][value][<?php echo $meOption ?>][unit]">
                            <?php foreach($unit as $_u):?>
                                <option value="<?php echo $_u ?>" <?php echo (isset($prevValues[$meOption]['unit']) && $prevValues[$meOption]['unit'] == $_u) ? "selected='selected'" : '' ?>><?php echo $_u ?></option>
                            <?php endforeach; ?>
                        </select>
                    </td>
            </tr>
        <?php endforeach; ?>
    </table>
</div>
