<?php

/**
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL).
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   	Payment Gateway
 * @package    	MercadoPago
 * @author      André Fuhrman (andrefuhrman@gmail.com)
 * @copyright  	Copyright (c) MercadoPago [http://www.mercadopago.com]
 * @license    	http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>

<a class="ch-close" onclick="closeRender();" style="z-index: 1002;">×</a>
<div class='mploading'><h3><strong><?php echo $this->__('Não há método de entrega disponível') ?></strong></h3></div><br />
<input id="buttonmp" class="ch-btn ch-big" type="button" value="<?php echo $this->__('Fechar') ?>" onclick="closeRender();" name="_eventId_next" tabindex="4"></input></center>

