<?php

/**
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL).
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   	Payment Gateway
 * @package    	MercadoPago
 * @author      André Fuhrman (andrefuhrman@gmail.com)
 * @copyright  	Copyright (c) MercadoPago [http://www.mercadopago.com]
 * @license    	http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>

<?php if ($this->getExpress() == true){ ?>
<link rel="stylesheet" href="<?php echo $this->getSkinUrl('css/chico/mpexpress.css'); ?>" />
<script type="text/javascript" src="<?php echo $this->getJsUrl('jquery/jquery.js'); ?>"></script>
<script type="text/javascript">
//<![CDATA[
	 var $j = jQuery.noConflict();
//]]>
</script>
<?php } ?>