<?php
$country = Mage::getStoreConfig('payment/mercadopago/country');
$coupon_mercadopago = Mage::getStoreConfig('payment/mercadopago_customticket/coupon_mercadopago');
$_code = $this->getMethodCode();
$grant_total = $this->helper('checkout/cart')->getQuote()->getGrandTotal();
$base_url = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK, true);
$route = $this->getRequest()->getRequestedRouteName();
$form_labels = array(
  "form" => array(
    "febraban_rules" => "Informações solicitadas em conformidade com as normas das circulares Nro. 3.461/09, 3.598/12 e 3.656/13 do Banco Central do Brasil.",
    "select" => "Selecione...",
    "name" => "Nome",
    "surname" => "Sobrenome",
    "docNumber" => "CPF",
    "address" => "Endereço",
    "number" => "Número",
    "city" => "Cidade",
    "state" => "Estado",
    "zipcode" => "CEP"
  ),
  "error" => array(
    //febraban
    "FEB001" => "Obrigatório o preenchimento do Nome",
    "FEB002" => "Obrigatório o preenchimento do Sobrenome",
    "FEB003" => "Obrigatório o preenchimento de um CPF válido",
    "FEB004" => "Obrigatório o preenchimento do Endereço",
    "FEB005" => "Obrigatório o preenchimento do Número residencial",
    "FEB006" => "Obrigatório informar a Cidade",
    "FEB007" => "Obrigatório informar o Estado",
    "FEB008" => "Obrigatório informar o CEP"
  )
);

$billingAddress = Mage::getSingleton('checkout/session')->getQuote()->getBillingAddress()->getData();

$customer = array(
  "firstname" => $billingAddress['firstname'],
  "lastname" => $billingAddress['lastname'],
  "address" => $billingAddress['street'],
  "addressnumber" => "",
  "city" => $billingAddress['city'],
  "state" => $billingAddress['region_id'],
  "zipcode" => $billingAddress['postcode']
);

$state_code = array(
  "485" => array("code" =>"AC", "state" => "Acre"),
  "486" => array("code" =>"AL", "state" => "Alagoas"),
  "487" => array("code" =>"AP", "state" => "Amapá"),
  "488" => array("code" =>"AM", "state" => "Amazonas"),
  "489" => array("code" =>"BA", "state" => "Bahia"),
  "490" => array("code" =>"CE", "state" => "Ceará"),
  "511" => array("code" =>"DF", "state" => "Distrito Federal"),
  "491" => array("code" =>"ES", "state" => "Espírito Santo"),
  "492" => array("code" =>"GO", "state" => "Goiás"),
  "493" => array("code" =>"MA", "state" => "Maranhão"),
  "494" => array("code" =>"MT", "state" => "Mato Grosso"),
  "495" => array("code" =>"MS", "state" => "Mato Grosso do Sul"),
  "496" => array("code" =>"MG", "state" => "Minas Gerais"),
  "497" => array("code" =>"PA", "state" => "Pará"),
  "498" => array("code" =>"PB", "state" => "Paraíba"),
  "499" => array("code" =>"PR", "state" => "Paraná"),
  "500" => array("code" =>"PE", "state" => "Pernambuco"),
  "501" => array("code" =>"PI", "state" => "Piauí"),
  "502" => array("code" =>"RJ", "state" => "Rio de Janeiro"),
  "503" => array("code" =>"RN", "state" => "Rio Grande do Norte"),
  "504" => array("code" =>"RS", "state" => "Rio Grande do Sul"),
  "505" => array("code" =>"RO", "state" => "Rondônia"),
  "506" => array("code" =>"RA", "state" => "Roraima"),
  "507" => array("code" =>"SC", "state" => "Santa Catarina"),
  "508" => array("code" =>"SP", "state" => "São Paulo"),
  "509" => array("code" =>"SE", "state" => "Sergipe"),
  "510" => array("code" =>"TO", "state" => "Tocantins")
);

?>
<script type="text/javascript">
if (typeof sendAnalyticsData === 'function') {
  sendAnalyticsData("<?php echo $_code ?>");
}
</script>
<fieldset class="conteiner-form-list">
  <link rel="stylesheet" href="<?php echo $this->getSkinUrl('mercadopago/css/style.css'); ?>?nocache=<?php echo rand(); ?>"/>
  <link rel="stylesheet" href="<?php echo $this->getSkinUrl('mercadopago/css/MPv1.css'); ?>?nocache=<?php echo rand(); ?>"/>

  <div id="mercadopago_checkout_custom_ticket">
    <ul class="form-list form-mercadopago" id="payment_form_<?php echo $_code ?>" style="display:none;">
      <li>
        <?php
        if ($coupon_mercadopago):
          $block = $this->getLayout()->createBlock('mercadopago/discount')->setCode($_code);
          echo $block->toHtml();
          ?>
          <script type="text/javascript">
          MercadoPagoCustom.getInstance().initDiscountTicket();
          </script>
          <?php
        endif;
        ?>
      </li>
      <li class="mercadopago-ticket-options">
        <?php $optionsTicket = $this->getTicketsOptions(); ?>
        <?php if (count($optionsTicket) == 1): ?>
          <input type="hidden" name="payment[<?php echo $_code; ?>][payment_method_ticket]" type="text" value="<?php echo $optionsTicket[0]['id']; ?>" id="payment_method_ticket"/>
        <?php else: ?>
          <ul>
            <?php foreach ($optionsTicket as $ticket): ?>
              <li class="mercadopago-ticket-option">
                <input type="radio" name="payment[<?php echo $_code; ?>][payment_method_ticket]" class="optionsTicketMp validate-one-required-by-name" value="<?php echo $ticket['id']; ?>">
                <label class="mercadopago-ticket-label">
                  <img src="<?php echo $ticket['secure_thumbnail']; ?>" alt="<?php echo $ticket['name']; ?>">
                  (<?php echo $ticket['name']; ?>)
                  <!--<span class="mercadopago-ticket-label-img"><img src="--><?php //echo $ticket['secure_thumbnail']; ?><!--" alt="--><?php //echo $ticket['name']; ?><!--"> </span>-->
                  <!--<span class="mercadopago-ticket-label-description">(--><?php //echo $ticket['name']; ?><!--)</span>-->
                </label>
              </li>
            <?php endforeach; ?>
          </ul>
        <?php endif; ?>

        <?php if(strtoupper($country) == "MLB"): ?>
          <div id="form-ticket">
            <div class="form-row">
              <div class="form-col-6">
                <label  for="firstname"><?php echo $form_labels['form']['name']; ?><em class="obrigatorio"> *</em></label>
                <input type="text" name="payment[<?php echo $_code; ?>][firstname]" data-checkout="firstname" id="firstname" class="form-control-mine required-entry-firstname">
              </div>

              <div class="form-col-6">
                <label  for="lastname"><?php echo $form_labels['form']['surname']; ?><em class="obrigatorio"> *</em></label>
                <input type="text" name="payment[<?php echo $_code; ?>][lastname]" data-checkout="lastname" id="lastname" class="form-control-mine required-entry-lastname">
              </div>
            </div>

            <div class="form-row">
              <div class="form-col-12">
                <label for="docNumber"><?php echo $form_labels['form']['docNumber']; ?><em class="obrigatorio"> *</em></label>
                <input type="text" name="payment[<?php echo $_code; ?>][doc-number]" class="form-control-mine required-entry-doc-number" maxlength="14" id="docNumber"
                onkeypress='execFormat(this,formatCPF)' onblur='clearTimeout()' data-checkout="docNumber">
              </div>
            </div>

            <div class="form-row">
              <div class="form-col-8">
                <label for="address"><?php echo $form_labels['form']['address']; ?><em class="obrigatorio"> *</em></label>
                <input type="text" name="payment[<?php echo $_code; ?>][address]" data-checkout="address" id="address" class="form-control-mine required-entry-address">
              </div>
              <div class="form-col-4">
                <label for="number"><?php echo $form_labels['form']['number']; ?><em class="obrigatorio"> *</em></label>
                <input type="text" name="payment[<?php echo $_code; ?>][address-number]" data-checkout="number" onkeypress="return event.charCode >= 48 && event.charCode <= 57"  class="form-control-mine required-entry-address-number">
              </div>
            </div>

            <div class="form-row">
              <div class="form-col-6">
                <label for="city"><?php echo $form_labels['form']['city']; ?><em class="obrigatorio"> *</em></label>
                <input type="text" name="payment[<?php echo $_code; ?>][address-city]" data-checkout="city" id="city" class="form-control-mine required-entry-address-city">
              </div>

              <div class="form-col-6">
                <label for="state"><?php echo $form_labels['form']['state']; ?><em class="obrigatorio"> *</em></label>
                <select name="payment[<?php echo $_code; ?>][address-state]" id="state" data-checkout="state" class="form-control-mine required-entry-address-state">
                  <option value=""><?php echo $form_labels['form']['select']; ?></option>
                  <option value="AC">Acre</option>
                  <option value="AL">Alagoas</option>
                  <option value="AP">Amapá</option>
                  <option value="AM">Amazonas</option>
                  <option value="BA">Bahia</option>
                  <option value="CE">Ceará</option>
                  <option value="DF">Distrito Federal</option>
                  <option value="ES">Espírito Santo</option>
                  <option value="GO">Goiás</option>
                  <option value="MA">Maranhão</option>
                  <option value="MT">Mato Grosso</option>
                  <option value="MS">Mato Grosso do Sul</option>
                  <option value="MG">Minas Gerais</option>
                  <option value="PA">Pará</option>
                  <option value="PB">Paraíba</option>
                  <option value="PR">Paraná</option>
                  <option value="PE">Pernambuco</option>
                  <option value="PI">Piauí</option>
                  <option value="RJ">Rio de Janeiro</option>
                  <option value="RN">Rio Grande do Norte</option>
                  <option value="RS">Rio Grande do Sul</option>
                  <option value="RO">Rondônia</option>
                  <option value="RA">Roraima</option>
                  <option value="SC">Santa Catarina</option>
                  <option value="SP">São Paulo</option>
                  <option value="SE">Sergipe</option>
                  <option value="TO">Tocantins</option>
                </select>
              </div>
            </div>

            <div class="form-row">
              <div class="form-col-6">
                <label for="zipcode"><?php echo $form_labels['form']['zipcode']; ?><em class="obrigatorio"> *</em></label>
                <input type="text" name="payment[<?php echo $_code; ?>][address-zipcode]" data-checkout="zipcode" id="zipcode"
                onkeypress="return event.charCode >= 48 && event.charCode <= 57" class="form-control-mine required-entry-address-zipcode">
              </div>
            </div>

            <div class="form-row">
              <div class="form-col-12">
                <span class="mensagem-febraban"><em>* </em><?php echo $form_labels['form']['febraban_rules']; ?></span>
              </div>
            </div>

          </div>

          <script>
          //<![CDATA[
          if (typeof Validation != 'undefined'){
            Validation.add('required-entry-firstname', "<?php echo $form_labels['error']['FEB001']; ?>", function(v) {
              return !Validation.get('IsEmpty').test(v);
            });

            Validation.add('required-entry-lastname', "<?php echo $form_labels['error']['FEB002']; ?>", function(v) {
              return !Validation.get('IsEmpty').test(v);
            });

            Validation.add('required-entry-doc-number', "<?php echo $form_labels['error']['FEB003']; ?>", function(v) {
              var Soma;
              var Resto;
              strCPF = v.replace(/[.-\s]/g, '')
              Soma = 0;

              if (strCPF == "00000000000"){
                return false;
              }
              for (i=1; i<=9; i++){
                Soma = Soma + parseInt(strCPF.substring(i-1, i)) * (11 - i);
              }
              Resto = (Soma * 10) % 11;
              if ((Resto == 10) || (Resto == 11)){
                Resto = 0;
              }
              if (Resto != parseInt(strCPF.substring(9, 10)) ){
                return false;
              }
              Soma = 0;
              for (i = 1; i <= 10; i++){
                Soma = Soma + parseInt(strCPF.substring(i-1, i)) * (12 - i);
              }
              Resto = (Soma * 10) % 11;
              if ((Resto == 10) || (Resto == 11)){
                Resto = 0;
              }
              if (Resto != parseInt(strCPF.substring(10, 11) ) ){
                return false;
              }
              return true;
            });

            Validation.add('required-entry-address', "<?php echo $form_labels['error']['FEB004']; ?>", function(v) {
              return !Validation.get('IsEmpty').test(v);
            });

            Validation.add('required-entry-address-number', "<?php echo $form_labels['error']['FEB005']; ?>", function(v) {
              return !Validation.get('IsEmpty').test(v);
            });

            Validation.add('required-entry-address-city', "<?php echo $form_labels['error']['FEB006']; ?>", function(v) {
              return !Validation.get('IsEmpty').test(v);
            });

            Validation.add('required-entry-address-state', "<?php echo $form_labels['error']['FEB007']; ?>", function(v) {
              return !Validation.get('IsEmpty').test(v);
            });

            Validation.add('required-entry-address-zipcode', "<?php echo $form_labels['error']['FEB008']; ?>", function(v) {
              return !Validation.get('IsEmpty').test(v);
            });
          }

          // Force the updating of values, when updating the html via ajax the value stays the same the first time set.
          document.querySelector("#form-ticket #firstname").value = "<?php echo $customer['firstname']?>";
          document.querySelector("#form-ticket #lastname").value = "<?php echo $customer['lastname']; ?>";
          document.querySelector("#form-ticket #address").value = "<?php echo preg_replace('/\s+/', ' ', $customer['address']); ?>";
          document.querySelector("#form-ticket #city").value = "<?php echo $customer['city']; ?>";
          document.querySelector("#form-ticket #state").value = "<?php echo $state_code[$customer['state']]['code']; ?>";
          document.querySelector("#form-ticket #zipcode").value = "<?php echo $customer['zipcode']; ?>";

          function execFormat(o,f){
              v_obj=o
              v_fun=f
              setTimeout('execFunction()',1)
          }

          function execFunction(){
              v_obj.value=v_fun(v_obj.value)
          }

          function formatCPF(v){
            //Remove tudo o que não é dígito
            v=v.replace(/\D/g,"")

            //Coloca um ponto entre o terceiro e o quarto dígitos
            v=v.replace(/(\d{3})(\d)/,"$1.$2")

            //Coloca um ponto entre o terceiro e o quarto dígitos
            //de novo (para o segundo bloco de números)
            v=v.replace(/(\d{3})(\d)/,"$1.$2")

            //Coloca um hífen entre o terceiro e o quarto dígitos
            v=v.replace(/(\d{3})(\d{1,2})$/,"$1-$2")

            return v
          }
          //]]>

          </script>

        <?php endif; ?>


        <input type="hidden" class="total_amount" name="total_amount" value="<?php echo $grant_total; ?>"/>
        <input type="hidden" class="amount" name="amount" value="<?php echo $grant_total; ?>"/>
        <input type="hidden" class="site_id" name="payment[<?php echo $_code; ?>][site_id]" value="<?php echo strtoupper($country); ?>"/>
        <input type="hidden" class="mercadopago-discount-amount" name="mercadopago-discount-amount" value="0"/>
        <input type="hidden" class="mercadopago-text-currency" value="<?php echo $this->__('$'); ?>">
        <input type="hidden" class="mercadopago-text-choice" value="<?php echo $this->__('Select'); ?>">
        <input type="hidden" class="mercadopago-text-default-issuer" value="<?php echo $this->__('Default issuer'); ?>">
        <input type="hidden" class="mercadopago-text-installment" value="<?php echo $this->__('Enter the card number'); ?>">
        <input type="hidden" class="mercado_base_url" value="<?php echo $base_url; ?>">
        <input type="hidden" class="mercado_route" value="<?php echo $route; ?>">
      </li>

    </ul>
  </div>
  <?php if ($this->getMethod()->getConfigData('communication') != ""): ?>
    <p class="communication"><?php echo $this->getMethod()->getConfigData('communication') ?></p>
  <?php endif; ?>
  <?php if ($this->getMethod()->getConfigData('banner_checkout') != ""): ?>
    <img src="<?php echo $this->getMethod()->getConfigData('banner_checkout'); ?>" class="banner_checkout_mp"/>
  <?php endif; ?>

</fieldset>
