<?php
$_htmlId = $this->getHtmlId() ? $this->getHtmlId() : '_' . uniqid();
$magentoCode = $this->getMagentoAttributes();
$sizeUnit = ['cm', 'mt'];
$weightUnit = ['kg', 'gr'];
$ocaCode = ['length','width','height', 'weight'];
$prevValues = [];
$unit = $sizeUnit;

$prevValues = $this->getStoredMappingValues();

?>

<div class="grid" id="grid<?php echo $_htmlId ?>">
    <table cellpadding="0" cellspacing="0" class="border">
        <tr class="headings" id="headings<?php echo $_htmlId ?>">
            <th><?php echo $this->__('Magento Product Attribute')?></th>
            <th><?php echo $this->__('MercadoEnvios')?></th>
            <th><?php echo $this->__('Magento Attribute Unit')?></th>
        </tr>
        <?php foreach($ocaCode as $key => $ocaOption):?>
            <tr id="<?php echo $ocaOption ?>">
                <td>
                    <select name="groups[mercadoenvios][fields][attributesmapping][value][<?php echo $ocaOption ?>][MagentoCode]">
                        <?php foreach($magentoCode as $option):?>
                            <option value="<?php echo $option->getAttributeCode() ?>" <?php echo ($prevValues[$key]['MagentoCode'] == $option->getAttributeCode()) ? "selected='selected'" : "" ?>><?php echo $option->getFrontendLabel() ?></option>
                        <?php endforeach; ?>
                    </select>
                </td>
                <td>
                    <select name="groups[mercadoenvios][fields][attributesmapping][value][<?php echo $ocaOption ?>][OcaCode]">
                        <?php foreach($ocaCode as $option):?>
                            <option value="<?php echo $option ?>" <?php echo ($prevValues[$key]['OcaCode'] == $option) ? "selected='selected'" : '' ?>><?php echo $option ?></option>
                        <?php endforeach; ?>
                    </select>
                </td>
                <?php if ($ocaOption == 'weight') : $unit = $weightUnit; endif;?>
                <td>
                    <select name="groups[mercadoenvios][fields][attributesmapping][value][<?php echo $ocaOption ?>][Unit]">
                        <?php foreach($unit as $_u):?>
                            <option value="<?php echo $_u ?>" <?php echo ($prevValues[$key]['Unit'] == $_u) ? "selected='selected'" : '' ?>><?php echo $_u ?></option>
                        <?php endforeach; ?>
                    </select>
                </td>

            </tr>
        <?php endforeach; ?>
    </table>
</div>
