<?php
$_htmlId = $this->getHtmlId() ? $this->getHtmlId() : '_' . uniqid();
$magentoCode = $this->_getAttributes();
$sizeUnit = ['cm', 'mt'];
$weightUnit = ['kg', 'gr'];
$meCode = ['length','width','height', 'weight'];
$prevValues = [];
$unit = $sizeUnit;

$prevValues = $this->_getStoredMappingValues();

?>

<div class="grid" id="grid<?php echo $_htmlId ?>">
    <table cellpadding="0" cellspacing="0" class="border">
        <tr class="headings" id="headings<?php echo $_htmlId ?>">
            <th><?php echo $this->__('Magento Product Attribute')?></th>
            <th><?php echo $this->__('MercadoEnvios')?></th>
            <th><?php echo $this->__('Magento Attribute Unit')?></th>
        </tr>
        <?php foreach($meCode as $key => $meOption):?>
            <tr id="<?php echo $meOption ?>">
                    <td>
                        <select name="groups[mercadoenvios][fields][attributesmapping][value][<?php echo $meOption ?>][attribute_code]">
                            <?php foreach($magentoCode as $option):?>
                                <option value="<?php echo $option->getAttributeCode() ?>" <?php echo ($prevValues[$key]['attribute_code'] == $option->getAttributeCode()) ? "selected='selected'" : "" ?>><?php echo $option->getFrontendLabel() ?></option>
                            <?php endforeach; ?>
                        </select>
                    </td>
                    <td>
                        <select name="groups[mercadoenvios][fields][attributesmapping][value][<?php echo $meOption ?>][me_code]">
                            <?php foreach($meCode as $option):?>
                                <option value="<?php echo $option ?>" <?php echo ($prevValues[$key]['me_code'] == $option) ? "selected='selected'" : '' ?>><?php echo $option ?></option>
                            <?php endforeach; ?>
                        </select>
                    </td>
                    <?php if ($meOption == 'weight') : $unit = $weightUnit; endif;?>
                    <td>
                        <select name="groups[mercadoenvios][fields][attributesmapping][value][<?php echo $meOption ?>][unit]">
                            <?php foreach($unit as $_u):?>
                                <option value="<?php echo $_u ?>" <?php echo ($prevValues[$key]['unit'] == $_u) ? "selected='selected'" : '' ?>><?php echo $_u ?></option>
                            <?php endforeach; ?>
                        </select>
                    </td>
            </tr>
        <?php endforeach; ?>
    </table>
</div>
