<?php
$_htmlId = $this->getHtmlId() ? $this->getHtmlId() : '_' . uniqid();

$magentoCode = Mage::getResourceModel('catalog/product_attribute_collection')
                ->addFieldToFilter('is_user_defined', 1)
                ->load();

$ocaCode = ['length','width','height', 'weight'];
$prevValues = [];
foreach ($this->getArrayRows() as $_rowId => $_row) {
    $prevValues[]= ['MagentoCode' => $_row->getData('MagentoCode'), 'OcaCode' => $_row->getData('OcaCode')];
}
?>

<div class="grid" id="grid<?php echo $_htmlId ?>">
    <table cellpadding="0" cellspacing="0" class="border">
        <tr class="headings" id="headings<?php echo $_htmlId ?>">
            <th><?php echo $this->__('Magento Product')?></th>
            <th><?php echo $this->__('MercadoEnvios')?></th>
        </tr>
        <?php foreach($ocaCode as $key => $ocaOption):?>
            <tr id="<?php echo $ocaOption ?>">
                    <td>
                        <select name="groups[mercadoenvios][fields][attributesmapping][value][<?php echo $ocaOption ?>][MagentoCode]">
                            <?php foreach($magentoCode as $option):?>
                                <option value="<?php echo $option->getAttributeCode() ?>" <?php echo ($prevValues[$key]['MagentoCode'] == $option->getAttributeCode()) ? "selected='selected'" : "" ?>><?php echo $option->getFrontendLabel() ?></option>
                            <? endforeach; ?>
                        </select>
                    </td>
                    <td>
                        <select name="groups[mercadoenvios][fields][attributesmapping][value][<?php echo $ocaOption ?>][OcaCode]">
                            <?php foreach($ocaCode as $option):?>
                                <option value="<?php echo $option ?>" <?php echo ($prevValues[$key]['OcaCode'] == $option) ? "selected='selected'" : '' ?>><?php echo $option ?></option>
                            <? endforeach; ?>
                        </select>
                    </td>
            </tr>
        <?php endforeach; ?>
    </table>
</div>


