<?php

/**
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL).
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   	Payment Gateway
 * @package    	MercadoPago
 * @author      André Fuhrman (andrefuhrman@gmail.com)
 * @copyright  	Copyright (c) MercadoPago [http://www.mercadopago.com]
 * @license    	http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

?>

<a class="ch-close" onclick="closeRender();" style="z-index: 1002;">×</a>
<form action="" id="mpform">
 <h1><?php echo $this->__('Escolha a forma de entrega') ?></h1>
<?php if (!($_shippingRateGroups = $this->getShippingRates())): ?>
    <p><?php echo $this->__('Desculpe, não há formas de entrega disponível nesse momento') ?></p>
<?php else: ?>
    <div id="mperror" class="error-msg" style="display:none;"><?php echo $this->__('É necessário escolher uma opção de envio') ;?></div>
    <dl class="mp-methods">
    <?php $shippingCodePrice = array(); ?>
    <?php $_sole = count($_shippingRateGroups) == 1; foreach ($_shippingRateGroups as $code => $_rates): ?>
        <dt><?php echo $this->getCarrierName($code) ?></dt>
        <dd>
            <ul>
            <?php $_sole = $_sole && count($_rates) == 1; foreach ($_rates as $_rate): ?>
                <?php $shippingCodePrice[] = "'".$_rate->getCode()."':".(float)$_rate->getPrice(); ?>
                <li>
                   <?php if ($_rate->getErrorMessage()): ?>
                    <ul class="messages"><li class="error-msg"><ul><li><?php echo $_rate->getErrorMessage() ?></li></ul></li></ul>
                   <?php else: ?>
                        <?php if ($_sole) : ?>
                        <span class="no-display"><input name="shipping_method" type="radio" value="<?php echo $_rate->getCode() ?>" id="s_method_<?php echo $_rate->getCode() ?>" checked="checked" /></span>
                        <?php else: ?>
                        <input name="shipping_method" type="radio" value="<?php echo $_rate->getCode() ?>" id="s_method_<?php echo $_rate->getCode() ?>"<?php if($_rate->getCode()===$this->getAddressShippingMethod()) echo ' checked="checked"' ?> class="radio"/>

                        <?php if ($_rate->getCode() === $this->getAddressShippingMethod()): ?>
                        <script type="text/javascript">
                            //<![CDATA[
                                lastPrice = <?php echo (float)$_rate->getPrice(); ?>;
                            //]]>
                        </script>
                        <?php endif; ?>

                        <?php endif; ?>
                        <label for="s_method_<?php echo $_rate->getCode() ?>"><?php echo $_rate->getMethodTitle() ?>
                        <?php $_excl = $this->getShippingPrice($_rate->getPrice(), $this->helper('tax')->displayShippingPriceIncludingTax()); ?>
                        <?php $_incl = $this->getShippingPrice($_rate->getPrice(), true); ?>
                        <?php echo $_excl; ?>
                        <?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
                            (<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)
                        <?php endif; ?>
                        </label>
                   <?php endif ?>
                </li>
            <?php endforeach; ?>
            </ul>
        </dd>
    <?php endforeach; ?>
    </dl>

<input id="buttonmp" class="ch-btn ch-big" type="button" value="<?php echo $this->__('Continuar') ?>" name="_eventId_next" tabindex="4"></input>
<?php if ($this->getAskcep() == 1){ ?>
<a id="changeCEP" href="#" onclick="changeCep()"><?php echo $this->__('Alterar o Cep') ?></a>
<?php } ;?>
</form>
<span id="mpload" style="display:none;">
<center><div class='mploading'><img id ='mpbt' src='<?php echo $this->getSkinUrl('images/mpexpress/loading.gif')  ;?>' alt='loading' /><p><?php echo $this->__('Seu pedido está sendo gerado. Por favor aguarde') ?></p></div></center>
</span>
<span id="mpload2" style="display:none;">
<center><div class='mploading'><img id ='mpbt' src='<?php echo $this->getSkinUrl('images/mpexpress/loading.gif')  ;?>' alt='loading' /><p><?php echo $this->__('Por favor aguarde') ?></p></div></center>
</span>

<script type="text/javascript">
 
 

         $j(document).ready(function() {
             methodssize();
        });

                     
            $j('#changeCEP').click(function(){
            $j('#mpform').hide();
            loadingsize();
            $j('#mpload2').show(); 
            var url = '<?php echo $this->getceppage();  ?>';
            doRequest(url);       
            });
 
           $j('#buttonmp').click(function(){
            
            var url = '<?php echo $this->getpostpage();  ?>';
            var shipmethod = $j('input[name=shipping_method]:checked', '#mpform').val();
            if (shipmethod != undefined ) {
                $j('#mpform').hide();
                loadingsize();
                $j('#mpload').show(); 
                var data = {shipping_method:shipmethod};
                doRequest(url,data);
            } else {
                $j('#mperror').show(); 
            }
             
     });

</script>
<?php endif; ?>