<?php
/**
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL).
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   	Payment Gateway
 * @package    	MercadoPago
 * @author      André Fuhrman (andrefuhrman@gmail.com)
 * @copyright  	Copyright (c) MercadoPago [http://www.mercadopago.com]
 * @license    	http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>



<form action="" id="mpform">
<ul class="form-list">

<li id="shipping-new-address-form">
             <div class="field">
                 <h1><?php echo $this->__('Insira seu cep') ?></h1>
               
                <div class="input-box">
                    <input type="text" name="zipcode" title="<?php echo $this->__('CEP') ?>" class="mp-input-text" id="zipcode" value="" />
                </div>
            </div>

        </li>
    </ul>

    <input id="buttonmp" class="ch-btn ch-big" type="button" value="<?php echo $this->__('Continuar') ?>" name="_eventId_next" tabindex="4"></input></form>
<span id="mpload" style="display:none;">
<center><div class='mploading'><img id ='mpbt' src='<?php echo $this->getSkinUrl('images/mpexpress/loading.gif')  ;?>' alt='loading' /><p><?php echo $this->__('Calculando valor do frete. Por favor aguarde') ?></p></div></center>
</span>
<a class="ch-close" onclick="closeRender();" style="z-index: 1002;">×</a>
<script type="text/javascript">
    
            $j(document).ready(function() {
            zipcodesize();
            });
  
            
          $j('#buttonmp').click(function(){
          $j('#mpform').hide();
          loadingsize();
          $j('#mpload').show();
          
          var cep = $j('#zipcode').val();
          
          var url =  '<?php echo $this->getpostpage();  ?>'
          var data = {zipcode:cep};
          doRequest(url,data);
           
     });
     
</script>
