<?php
$page_redirec = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK,true) . "checkout/onepage/success";
?>

<link rel="stylesheet" href="<?php echo $this->getSkinUrl('mercadopago/css/style.css'); ?>" />

<script>
    window.onload = function() {
      contagem_tempo();  
    };
    
    function contagem_tempo(){
        if(document.getElementById("segundos_redirect") != null){
            var segundos = document.getElementById("segundos_redirect").innerHTML;
            
            segundos = segundos - 1;
             
            if (segundos == -1) {
                segundos = 0;
                location.href = "<?php echo $page_redirec; ?>";
                return;
            }   
            document.getElementById("segundos_redirect").innerHTML = segundos ;
            timerID = setTimeout("contagem_tempo()", 1000);
        }
    }   
    
</script>

<div id="mensagem_mp">
    
    <?php if($payment_method_id == "bolbradesco"): ?>
    
        <?php
            /*
             *
             * Processo para boleto
             *
             */
        ?>
        
        <h4>Pronto, seu pedido foi gerado com sucesso!</h4>
        
        <p>
            Gere o boleto e pague-o onde quiser.
        </p>
        <p>
            <a href="<?php echo $payment['activation_uri']; ?>" target="_blank" class="btn-boleto"> Gerar boleto </a>    
        </p>
        
        <p>Será aprovado até 2 dias úteis.</p>
        
    <?php else: ?>
        
        <?php
            /*
             *
             * Processo para cartão
             *
             */
        ?>
        
        <?php if($status == "approved"): ?>
        
            <h4>Pronto, seu pagamento foi aprovado!</h4>
                
            <p>
                <img src="<?php echo $this->getSkinUrl('mercadopago/images/loading.gif')  ;?>" alt="loading" />
                Em <span id="segundos_redirect">6</span> segundos <a href="<?php echo $page_redirec; ?>">você será redirecionado para tela de finalização.</a>
            </p>
            
        <?php elseif($status == "pending" || $status == "in_process"): ?>
            
            <h4>Estamos processando o pagamento</h4>
            <p class="status"><?php  echo $mensagem; ?></p>
            
            <p>
                <img src="<?php echo $this->getSkinUrl('mercadopago/images/loading.gif')  ;?>" alt="loading" />
                Em <span id="segundos_redirect">10</span> segundos <a href="<?php echo $page_redirec; ?>">você será redirecionado para tela de finalização.</a>
            </p>
        
        <?php elseif($status == "rejected"): ?>
            
            <h4>O seu pagamento não foi processado.</h4>
            <p class="status"><?php  echo $mensagem; ?></p>
            <p><a class="voltar" href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK,true); ?>sales/order/reorder/order_id/<?php echo $order->getId(); ?> ">Voltar para o carrinho</a></p>
            
        <?php elseif(!$status): ?>
        
            <h4>O seu pagamento não foi processado.</h4>        
            <p><a class="voltar" href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK,true); ?>">Voltar</a></p>
            
        <?php endif; ?>
    
    <?php endif; ?>

</div>



<div id="logo_mp">
    <img src="https://secure.mlstatic.com/components/resources/mp/desktop/css/assets/desktop-logo-mercadopago.png" /> 
</div>
