<p><strong><?php echo $this->getMethod()->getTitle() ?></strong></p>

<?php if($this->getOrder()->getAdditionalInformation('cardholderName') != ""): ?>
    <p><?php echo $this->__('Nome do Comprador: %s', $this->htmlEscape($this->getOrder()->getAdditionalInformation('cardholderName'))); ?></p>
<?php endif; ?>

<?php if($this->getOrder()->getAdditionalInformation('trunc_card') != ""): ?>
    <p><?php echo $this->__('Cartão: %s', $this->htmlEscape($this->getOrder()->getAdditionalInformation('trunc_card'))); ?></p>
<?php endif; ?>

<?php if($this->getOrder()->getAdditionalInformation('payment_method') != ""): ?>
    <p><?php echo $this->__('Método de Pagamento: %s', $this->htmlEscape($this->getOrder()->getAdditionalInformation('payment_method'))); ?></p>
<?php endif; ?>

<?php if($this->getOrder()->getAdditionalInformation('statement_descriptor') != ""): ?>
    <p><?php echo $this->__('Identificação na Fatura: %s', $this->htmlEscape($this->getOrder()->getAdditionalInformation('statement_descriptor'))); ?></p>
<?php endif; ?>

<?php if($this->getOrder()->getAdditionalInformation('payment_id') != ""): ?>
    <p><?php echo $this->__('Numero de Pagamento (MercadoPago): %s', $this->htmlEscape($this->getOrder()->getAdditionalInformation('payment_id'))); ?></p>
<?php endif; ?>

<?php if($this->getOrder()->getAdditionalInformation('status') != ""): ?>
    <p><?php echo $this->__('Status de Pagamento: %s (%s)', $this->htmlEscape($this->getOrder()->getAdditionalInformation('status')), $this->htmlEscape($this->getOrder()->getAdditionalInformation('status_detail'))); ?></p>
<?php endif; ?>