
<fieldset class="form-list">
    <link rel="stylesheet" href="<?php echo $this->getSkinUrl('mercadopago/css/style.css'); ?>" />
    
    <?php $_code = $this->getMethodCode(); ?>
    <?php $_country = $this->getMethodCountry(); ?>

    <?php if($this->getMethod()->getConfigData('banner_checkout') != ""): ?>
        <img src="<?php echo $this->getMethod()->getConfigData('banner_checkout'); ?>"  class="banner_checkout_mp"/>
    <?php endif;?>
    
    <div id="mp-form-boleto">
        <ul class="form-list form-mercadopago" id="payment_form_<?php  echo $_code ?>" style="display:none;" >
            <li style="display:none;">
                <input type="hidden" name="payment[doc_number]" type="text" value="" />
                <input type="hidden" name="payment[card_token_id]" type="text" value="" />
                <input type="hidden" name="payment[installments]" type="text" value="1" />
                <input type="hidden" name="payment[payment_method_boleto]" type="text" value="bolbradesco"/>
            </li>    
        </ul>
    </div>

</fieldset>
