<?php

/**
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL).
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   	Payment Gateway
 * @package    	MercadoPago
 * @author      André Fuhrman (andrefuhrman@gmail.com)
 * @copyright  	Copyright (c) MercadoPago [http://www.mercadopago.com]
 * @license    	http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>


<script src="<?php echo $this->getJsUrl('chico/chico-0.11.js'); ?>"></script>
<script type="text/javascript">

    var $j = jQuery.noConflict(); 

    $j("#example").tooltip();
    
    foo = $j("#mpbttop").modal({
    "content": "<div id='mpmodal'><center><div class='mploading'><img id ='mpbt' src='<?php echo $this->getSkinUrl('images/mpexpress/loading.gif')  ;?>' alt='loading' /><p><?php echo $this->__('Iniciando o Checkout Expresso do MercadoPago') ?></p></div></center></div>",
    "width": "300px",
    "height": "150px",
    "closable" : false
    });
    
    foo2 = $j("#mpbtbaixo").modal({
    "content": "<div id='mpmodal'><center><div class='mploading'><img id ='mpbt' src='<?php echo $this->getSkinUrl('images/mpexpress/loading.gif')  ;?>' alt='loading' /><p><?php echo $this->__('Iniciando o Checkout Expresso do MercadoPago') ?></p></div></center></div>",
    "width": "300px",
    "height": "150px",
    "closable" : false
    });
    
    function defaultContent(){
           if (foo != undefined){foo.content("<div id='mpmodal'><center><div class='mploading'><img id ='mpbt' src='<?php echo $this->getSkinUrl('images/mpexpress/loading.gif')  ;?>' alt='loading' /><p>Iniciando o Checkout Expresso do MercadoPago</p></div></center></div>")}; 
           if (foo2 != undefined){foo2.content("<div id='mpmodal'><center><div class='mploading'><img id ='mpbt' src='<?php echo $this->getSkinUrl('images/mpexpress/loading.gif')  ;?>' alt='loading' /><p>Iniciando o Checkout Expresso do MercadoPago</p></div></center></div>")}; 

    }
    function zipcodesize(){
            if (foo != undefined){foo.width("300px")};
            if (foo != undefined){foo.height("150px")};
            if (foo2 != undefined){foo2.width("300px")};
            if (foo2 != undefined){foo2.height("150px")};
    }
    
     function loadingsize(){
            if (foo != undefined){foo.width('300px')};
            if (foo != undefined){foo.height("150px")};
            if (foo2 != undefined){foo2.width('300px')};
            if (foo2 != undefined){foo2.height("150px")};
    }
    
    function methodssize(){
             if (foo != undefined){foo.width("400px")};
             if (foo != undefined){foo.height("400px")};
             if (foo2 != undefined){foo2.width("400px")};
             if (foo2 != undefined){foo2.height("400px")};
    }
    
     function checkoutsize(){
             if (foo != undefined){foo.width("750px")};
             if (foo != undefined){foo.height("480px")};
             if (foo2 != undefined){foo2.width("750px")};
             if (foo2 != undefined){foo2.height("480px")};
    }

     $j("#mpbttop").click(function(){
          $j.ajax({
          url: '<?php echo $this->getcheckoutexpress();  ?>',
          async: true,
          success: function(data){
              $j('#mpmodal').html(data);
              }
          });      
     });
     $j("#mpbtbaixo").click(function(){
          $j.ajax({
          url: '<?php echo $this->getcheckoutexpress();  ?>',
          async: true,
          success: function(data){
              $j('#mpmodal').html(data);
              }
          });      
     }); 
 
    function doRequest(url,send){
    request  = $j.ajax({
          url: url,
          async: true,
          data: send,
          success: function(data){
              $j('#mpload').hide();
              $j('#mpmodal').html(data);
              }
          });   
    }
    
    function closeRender(){
        defaultContent();
      if (foo != undefined){foo.hide()};
      if (foo2 != undefined){foo2.hide()};
        loadingsize();
        request.abort();
    };
    
    
    
    
    
     
    var tip = $j("#mpbttop").tooltip();
    var tip2 = $j("#mpbtbaixo").tooltip();
    

    

 
</script>


