<p><strong><?php echo $this->getMethod()->getTitle() ?></strong></p>

<?php if( Mage::app()->getRequest()->getRouteName() == "sales" || Mage::app()->getFrontController()->getAction()->getFullActionName() == 'checkout_onepage_success' ): ?>

    <?php
        $info_payment = $this->getInfoPayment();
    ?>


    <?php if(isset($info_payment['payment_id']) && $info_payment['payment_id']['value'] != ""): ?>
        <p><?php echo $this->__('Payment Id (Mercado Pago): %s', $info_payment['payment_id']['value']); ?></p>
    <?php endif; ?>

    <?php if(isset($info_payment['status']) && $info_payment['status']['value'] != ""): ?>
        <p><?php echo $this->__('Payment Status: %s', $info_payment['status']['value']); ?></p>
    <?php endif; ?>

    <?php if(isset($info_payment['status_detail']) && $info_payment['status_detail']['value'] != ""): ?>
        <p><?php echo $this->__('Payment Status Detail: %s', $info_payment['status_detail']['value']); ?></p>
    <?php endif; ?>


<?php endif;?>
