<style>
    #btn-boleto-mercadopago{
        font-size: 1.25em;
        text-align: center;
        line-height: 1.25em;
        padding: 6px 12px;
        font-family: 'Lato',sans-serif;
        font-weight: 400;
        background-color: #36A1F1;
        background-image: -webkit-gradient(linear,left top,left bottom,color-stop(0%,#36A1F1),color-stop(100%,#0F79C9));
        background-image: -webkit-linear-gradient(#36A1F1,#0F79C9);
        background-image: -moz-linear-gradient(#36A1F1,#0F79C9);
        background-image: -o-linear-gradient(#36A1F1,#0F79C9);
        background-image: linear-gradient(#36A1F1,#0F79C9);
        -webkit-box-shadow: inset 0 1px #97DCFF;
        box-shadow: 0 1px #97DCFF inset;
        color: #FFF!important;
        border: 1px solid #0D6FB9;
        border-radius: 4px 4px 4px 4px;
        cursor: pointer;
        display: inline-block;
        text-decoration:none;
    }
    #btn-boleto-mercadopago:hover{
        background-color:#4CBFF8;
        background-image:linear-gradient(#4CBFF8,#1699DF);
        box-shadow:0 1px #B6EBFF inset;
        background-image:-webkit-gradient(linear,left top,left bottom,color-stop(0%,#4CBFF8),color-stop(100%,#1699DF));
        background-image:-webkit-linear-gradient(#4CBFF8,#1699DF);
        background-image:-moz-linear-gradient(#4CBFF8,#1699DF);
        background-image:-o-linear-gradient(#4CBFF8,#1699DF);
        background-image:linear-gradient(#4CBFF8,#1699DF);-webkit-box-shadow:inset 0 1px #B6EBFF;
        border:1px solid #1890D3;
        color:#FFF;
        text-decoration:none;
    }
    #box-mercadopago{
        float:left;
        text-align: left;
        margin: 10px 0;
    }
    
    #title-mercadopago{
        text-transform:uppercase;
    }
    
    #logo-mercadopago{
        margin: 10px 0;
    }
</style>

<div id="box-mercadopago">
    
    <?php
    //mensagem apenas para checkout transparent
    if(!isset($_REQUEST['preference_id'])):
    ?>
    <h5>
        <b>
            <?php echo $this->__('Método de Pagamento'); ?>
        </b>
    </h5>
    
    <?php
        $order = $this->getOrder();
        
        $total = $order->getBaseGrandTotal();
        if (!$total) {
            $total = $order->getBasePrice() + $order->getBaseShippingAmount();
        }
        
        $total = number_format($total, 2, '.', '');
        
        $payment = $order->getPayment();
        
            if($payment->getAdditionalInformation('payment_method') == 'bolbradesco'):
        ?>
        
            <p>
                <?php echo $this->__('Gere o boleto e pague-o onde quiser.'); ?>
            </p>
            <p>
                <?php echo $this->__('Será aprovado até 2 dias úteis.'); ?>
            </p>
            <a href="<?php echo urldecode($this->htmlEscape($payment->getAdditionalInformation('activation_uri'))); ?>" target="_blank" id="btn-boleto-mercadopago">
                <?php echo $this->__('Gerar Boleto'); ?>
            </a>
        
        <?php else: ?>
            
            <?php
            $title = "";
            $msg = "";
            
            switch ($payment->getAdditionalInformation('status')){
                case "approved":
                    $title = $this->__('O seu pagamento foi aprovado!');
                    $msg = "";
                    break;
                
                case "in_process":
                    $title = $this->__('Estamos processando o pagamento.');
                    $msg = "Em menos de 2 dias úteis você será avisado por e-mail se foi creditado ou se precisarmos de mais informações.";
                    break;
                
                case "pending":
                    $title = $this->__('Estamos processando o pagamento.');
                    $msg = "Em menos de 1 hora, nós enviaremos o resultado por e-mail.";
                    break;
                
                case "rejected":
                    $title = $this->__('O seu pagamento não foi processado.');
                    
                    switch ($payment->getAdditionalInformation('status_detail')){
                        case "cc_rejected_bad_filled_card_number":
                            $msg = $this->__('Verifique o número do cartão.');
                            break;
                        
                        case "cc_rejected_bad_filled_date":
                            $msg = $this->__('Verifique a data de validade.');
                            break;
                        
                        case "cc_rejected_bad_filled_other":
                            $msg = $this->__('Verifique os dados.');
                            break;
                        
                        case "cc_rejected_bad_filled_security_code":
                            $msg = $this->__('Verifique o código de segurança.');
                            break;
                        
                        case "cc_rejected_blacklist":
                            $msg = $this->__('Não foi possível processar o pagamento.');
                            break;
                        
                        case "cc_rejected_call_for_authorize":
                            $msg = $this->__('Você precisa autorizar com a %s o pagamento de R$ %s ao MercadoPago', strtoupper($payment->getAdditionalInformation('payment_method')), strtoupper($total));
                            break;
                        
                        case "cc_rejected_card_disabled":
                            $msg = $this->__('Ligue para %s e ative o seu cartão.  <br/>
                                    O telefone está no verso do seu cartão de crédito.', strtoupper($payment->getAdditionalInformation('payment_method')));
                            break;
                        
                        case "cc_rejected_card_error":
                            $msg = $this->__('Não foi possível processar o pagamento.');
                            break;
                        
                        case "cc_rejected_duplicated_payment":
                            $msg = $this->__('Você já fez o pagamento deste valor. <br/>
                                    Se você precisa pagar novamente use outro cartão ou outro meio de pagamento.');
                            break;
                        
                        case "cc_rejected_high_risk":
                            $msg = $this->__('O seu pagamento foi recusado. <br/>
                                    Recomendamos que você pague com outro dos meios de pagamento oferecidos, preferencialmente à vista.');
                            break;
                        
                        case "cc_rejected_insufficient_amount":
                            $msg = $this->__('O seu %s não tem limite suficiente.', strtoupper($payment->getAdditionalInformation('payment_method')));
                            break;
                        
                        case "cc_rejected_invalid_installments":
                            $msg = $this->__('%s não processa pagamentos em %s parcelas.', strtoupper($payment->getAdditionalInformation('payment_method')), $payment->getAdditionalInformation('installments'));
                            break;
                        
                        case "cc_rejected_max_attempts":
                            $msg = $this->__('Você atingiu o limite de tentativas permitidas. <br/>
                                    Use outro cartão ou outro meio de pagamento.');
                            break;
                        
                        case "cc_rejected_other_reason":
                            $msg = $this->__('%s não processou o pagamento.', strtoupper($payment->getAdditionalInformation('payment_method')));
                            break;
                    }
                break;
            }
            ?>
            
            <p>
                <b id="title-mercadopago">
                    <?php echo $title; ?>
                </b>
            </p>
            <p>
                <i>
                    <?php echo $msg; ?>
                </i>
            </p>
            
            <br />
            
            <?php if($payment->getAdditionalInformation('cardholderName') != ""): ?>
                <p><?php echo $this->__('Titular do Cartão: %s', $this->htmlEscape($payment->getAdditionalInformation('cardholderName'))); ?></p>
            <?php endif; ?>
            
            <?php if($payment->getAdditionalInformation('trunc_card') != ""): ?>
                <p><?php echo $this->__('Cartão: %s', $this->htmlEscape($payment->getAdditionalInformation('trunc_card'))); ?></p>
            <?php endif; ?>
            
            <?php if($payment->getAdditionalInformation('payment_method') != ""): ?>
                <p><?php echo $this->__('Método de Pagamento: %s', $this->htmlEscape($payment->getAdditionalInformation('payment_method'))); ?></p>
            <?php endif; ?>
            
            <?php if($payment->getAdditionalInformation('expiration_date') != ""): ?>
                <p><?php echo $this->__('Data de expiração: %s', $this->htmlEscape($payment->getAdditionalInformation('expiration_date'))); ?></p>
            <?php endif; ?>
            
            <?php if($payment->getAdditionalInformation('installments') != ""): ?>
                <p><?php echo $this->__('Parcelas: %s', $this->htmlEscape($payment->getAdditionalInformation('installments'))); ?></p>
            <?php endif; ?>
            
            <?php if($payment->getAdditionalInformation('statement_descriptor') != ""): ?>
                <p><?php echo $this->__('Identificação na Fatura: %s', $this->htmlEscape($payment->getAdditionalInformation('statement_descriptor'))); ?></p>
            <?php endif; ?>
            
            <?php if($payment->getAdditionalInformation('payment_id') != ""): ?>
                <p><?php echo $this->__('Numero de Pagamento (MercadoPago): %s', $this->htmlEscape($payment->getAdditionalInformation('payment_id'))); ?></p>
            <?php endif; ?>
            
            <?php if($payment->getAdditionalInformation('status') != ""): ?>
                <p><?php echo $this->__('Status de Pagamento: %s (%s)', $this->htmlEscape($payment->getAdditionalInformation('status')), $this->htmlEscape($payment->getAdditionalInformation('status_detail'))); ?></p>
            <?php endif; ?>    
            
            
        <?php endif; ?>
    
        <div id="logo-mercadopago">
            <img src="https://secure.mlstatic.com/components/resources/mp/desktop/css/assets/desktop-logo-mercadopago.png" /> 
        </div>
    <?php endif; ?>
</div>

