<style>
    #btn-boleto-mercadopago{
        font-size: 1.25em;
        text-align: center;
        line-height: 1.25em;
        padding: 6px 12px;
        font-family: 'Lato',sans-serif;
        font-weight: 400;
        background-color: #36A1F1;
        background-image: -webkit-gradient(linear,left top,left bottom,color-stop(0%,#36A1F1),color-stop(100%,#0F79C9));
        background-image: -webkit-linear-gradient(#36A1F1,#0F79C9);
        background-image: -moz-linear-gradient(#36A1F1,#0F79C9);
        background-image: -o-linear-gradient(#36A1F1,#0F79C9);
        background-image: linear-gradient(#36A1F1,#0F79C9);
        -webkit-box-shadow: inset 0 1px #97DCFF;
        box-shadow: 0 1px #97DCFF inset;
        color: #FFF!important;
        border: 1px solid #0D6FB9;
        border-radius: 4px 4px 4px 4px;
        cursor: pointer;
        display: inline-block;
        text-decoration:none;
    }
    #btn-boleto-mercadopago:hover{
        background-color:#4CBFF8;
        background-image:linear-gradient(#4CBFF8,#1699DF);
        box-shadow:0 1px #B6EBFF inset;
        background-image:-webkit-gradient(linear,left top,left bottom,color-stop(0%,#4CBFF8),color-stop(100%,#1699DF));
        background-image:-webkit-linear-gradient(#4CBFF8,#1699DF);
        background-image:-moz-linear-gradient(#4CBFF8,#1699DF);
        background-image:-o-linear-gradient(#4CBFF8,#1699DF);
        background-image:linear-gradient(#4CBFF8,#1699DF);-webkit-box-shadow:inset 0 1px #B6EBFF;
        border:1px solid #1890D3;
        color:#FFF;
        text-decoration:none;
    }
    #box-mercadopago{
        float:left;
        text-align: left;
        margin: 10px 0;
    }
    
    #title-mercadopago{
        text-transform:uppercase;
    }
    
    #logo-mercadopago{
        margin: 10px 0;
    }
</style>

<div id="box-mercadopago">
    
    <?php
    //mensagem apenas para checkout transparent
    if(!isset($_REQUEST['preference_id'])):
    ?>
    <h5>
        <b>
            <?php echo $this->__('Payment Method'); ?>
        </b>
    </h5>
    
    <?php
        $order = $this->getOrder();
        
        $total = $order->getBaseGrandTotal();
        if (!$total) {
            $total = $order->getBasePrice() + $order->getBaseShippingAmount();
        }
        
        $total = number_format($total, 2, '.', '');
        
        $payment = $order->getPayment();
        
            if($payment->getAdditionalInformation('payment_type_id') == 'ticket'):
        ?>
        
            <p>
                <?php echo $this->__('Generate the ticket and pay it wherever you want.'); ?>
            </p>
            <p>
                <?php echo $this->__('Will be approved within 2 business days.'); ?>
            </p>
            <a href="<?php echo urldecode($this->htmlEscape($payment->getAdditionalInformation('activation_uri'))); ?>" target="_blank" id="btn-boleto-mercadopago">
                <?php echo $this->__('Generate Ticket'); ?>
            </a>

        <?php else: ?>
            
            <?php
            $title = "";
            $msg = "";
            
            switch ($payment->getAdditionalInformation('status')){
                case "approved":
                    $title = $this->__('Done, your payment was accredited!');
                    $msg = "";
                    break;
                
                case "in_process":
                    $title = $this->__('We are processing the payment.');
                    $msg = $this->__('In less than 2 business days we will tell you by e-mail if it is accredited or if we need more information.');
                    break;
                
                case "pending":
                    $title = $this->__('We are processing the payment.');
                    $msg = $this->__('In less than an hour we will send you by e-mail the result.');
                    break;
                
                case "rejected":
                    $title = $this->__('We could not process your payment.');
                    
                    switch ($payment->getAdditionalInformation('status_detail')){
                        case "cc_rejected_bad_filled_card_number":
                            $msg = $this->__('Check the card number.');
                            break;
                        
                        case "cc_rejected_bad_filled_date":
                            $msg = $this->__('Check the expiration date.');
                            break;
                        
                        case "cc_rejected_bad_filled_other":
                            $msg = $this->__('Check the data.');
                            break;
                        
                        case "cc_rejected_bad_filled_security_code":
                            $msg = $this->__('Check the security code.');
                            break;
                        
                        case "cc_rejected_blacklist":
                            $msg = $this->__('We could not process your payment.');
                            break;
                        
                        case "cc_rejected_call_for_authorize":
                            $msg = $this->__('You must authorize to %s the payment of $ %s to MercadoPago.', strtoupper($payment->getAdditionalInformation('payment_method')), strtoupper($total));
                            break;
                        
                        case "cc_rejected_card_disabled":
                            $msg = $this->__('Call %s to activate your card.<br/>The phone is on the back of your card.', strtoupper($payment->getAdditionalInformation('payment_method')));
                            break;
                        
                        case "cc_rejected_card_error":
                            $msg = $this->__('We could not process your payment.');
                            break;
                        
                        case "cc_rejected_duplicated_payment":
                            $msg = $this->__('You already made a payment by that value.<br/>If you need to repay, use another card or other payment method.');
                            break;
                        
                        case "cc_rejected_high_risk":
                            $msg = $this->__('Your payment was rejected.<br/>Choose another payment method, we recommend cash methods.');
                            break;
                        
                        case "cc_rejected_insufficient_amount":
                            $msg = $this->__('Your %s do not have sufficient funds.', strtoupper($payment->getAdditionalInformation('payment_method')));
                            break;
                        
                        case "cc_rejected_invalid_installments":
                            $msg = $this->__('%s does not process payments in %s installments.', strtoupper($payment->getAdditionalInformation('payment_method')), $payment->getAdditionalInformation('installments'));
                            break;
                        
                        case "cc_rejected_max_attempts":
                            $msg = $this->__('You have got to the limit of allowed attempts.<br/>Choose another card or another payment method.');
                            break;
                        
                        case "cc_rejected_other_reason":
                            $msg = $this->__('%s did not process the payment.', strtoupper($payment->getAdditionalInformation('payment_method')));
                            break;
                    }
                break;
            }
            ?>
            
            <p>
                <b id="title-mercadopago">
                    <?php echo $title; ?>
                </b>
            </p>
            <p>
                <i>
                    <?php echo $msg; ?>
                </i>
            </p>
            
            <br />
            
            <?php if($payment->getAdditionalInformation('cardholderName') != ""): ?>
                <p><?php echo $this->__('Card Holder Name: %s', $this->htmlEscape($payment->getAdditionalInformation('cardholderName'))); ?></p>
            <?php endif; ?>
            
            <?php if($payment->getAdditionalInformation('trunc_card') != ""): ?>
                <p><?php echo $this->__('Card Number: %s', $this->htmlEscape($payment->getAdditionalInformation('trunc_card'))); ?></p>
            <?php endif; ?>
            
            <?php if($payment->getAdditionalInformation('payment_method') != ""): ?>
                <p><?php echo $this->__('Payment Method: %s', $this->htmlEscape($payment->getAdditionalInformation('payment_method'))); ?></p>
            <?php endif; ?>
            
            <?php if($payment->getAdditionalInformation('expiration_date') != ""): ?>
                <p><?php echo $this->__('Expiration Date: %s', $this->htmlEscape($payment->getAdditionalInformation('expiration_date'))); ?></p>
            <?php endif; ?>
            
            <?php if($payment->getAdditionalInformation('installments') != ""): ?>
                <p><?php echo $this->__('Installments: %s', $this->htmlEscape($payment->getAdditionalInformation('installments'))); ?></p>
            <?php endif; ?>
            
            <?php if($payment->getAdditionalInformation('statement_descriptor') != ""): ?>
                <p><?php echo $this->__('Statement Descriptor: %s', $this->htmlEscape($payment->getAdditionalInformation('statement_descriptor'))); ?></p>
            <?php endif; ?>
            
            <?php if($payment->getAdditionalInformation('payment_id') != ""): ?>
                <p><?php echo $this->__('Payment id (MercadoPago): %s', $this->htmlEscape($payment->getAdditionalInformation('payment_id'))); ?></p>
            <?php endif; ?>
            
            <?php if($payment->getAdditionalInformation('status') != ""): ?>
                <p><?php echo $this->__('Payment Status: %s (%s)', $this->htmlEscape($payment->getAdditionalInformation('status')), $this->htmlEscape($payment->getAdditionalInformation('status_detail'))); ?></p>
            <?php endif; ?>    
            
            
        <?php endif; ?>
    
        <div id="logo-mercadopago">
            <img src="https://secure.mlstatic.com/components/resources/mp/desktop/css/assets/desktop-logo-mercadopago.png" /> 
        </div>
    <?php endif; ?>
</div>

