
<fieldset class="form-list">
    <link rel="stylesheet" href="<?php echo $this->getSkinUrl('mercadopago/css/style.css'); ?>" />
    <?php $_code = $this->getMethodCode(); ?>
    <?php $_country = $this->getMethodCountry(); ?>

    <?php if($this->getMethod()->getConfigData('banner_checkout') != ""): ?>
        <img src="<?php echo $this->getMethod()->getConfigData('banner_checkout'); ?>"  class="banner_checkout_mp"/>
    <?php endif;?>
    
    <div id="mp-form-boleto">
        <ul class="form-list form-mercadopago" id="payment_form_<?php  echo $_code ?>" style="display:none;" >
            <li>
                
                <?php
                $optionsTicket = $this->getTicketsOptions();
                if(count($optionsTicket) == 1){ ?>
                    <input type="hidden" name="payment[payment_method_boleto]" type="text" value="<?php echo $optionsTicket[0]['id']; ?>" id="payment_method_boleto" />
                <?php } else { ?>
                        
                    <?php
                    foreach($optionsTicket as $ticket){ ?>
                        <input type="radio" name="payment[payment_method_boleto]" class="optionsTicketMp" value="<?php echo $ticket['id']; ?>"> <img src="<?php echo $ticket['secure_thumbnail']; ?>"> (<?php echo $ticket['name']; ?>) <br/>
                    <?php } ?>
                <?php } ?>
            </li>
            
        </ul>
    </div>

</fieldset>
