<script type="text/javascript" src="https://secure.mlstatic.com/modules/javascript/analytics.js"></script>

<script>
    function sendAnalyticsData(type) {
        var mpanalytics_data = <?php echo json_encode($this->getAnalyticsData());?>;
        if (mpanalytics_data != false) {
            var MA = ModuleAnalytics;
            if (type === 'mercadopago_custom') {
                MA.setPublicKey(mpanalytics_data.custom_analytics_key);
                MA.setToken(null);
            } else if (type === 'mercadopago_customticket') {
                MA.setToken(mpanalytics_data.ticket_analytics_key);
                MA.setPublicKey(null);
            } else {
                MA.setToken(mpanalytics_data.standard_analytics_key);
                MA.setPublicKey(null);
            }
            MA.setPlatform("Magento");
            MA.setPlatformVersion(mpanalytics_data.platform_version);
            MA.setModuleVersion(mpanalytics_data.module_version);
            MA.setPayerEmail(mpanalytics_data.email);
            MA.setUserLogged(mpanalytics_data.user_logged);

            MA.setInstalledModules(mpanalytics_data.payment_methods);
            MA.post();
        }
    }

</script>

