<?php
$link_to_calculator = Mage::getBaseUrl().'mercadopago/calculatorPayment';
if( $this->isAvailableCalculator() & $this->isPageToShow($this->getNameInLayout()) ): ?>
    <div id="mercadopago_calculator_link">
        <a href="javascript:void(0)" onclick="MercadoPagoCustom.showPopup()">
            <?php echo $this->__('Calculate your payments ')?>
        </a>
        <p><?php echo $this->__('with ')?></p>
        <img id="meli-logo" src="<?php echo $this->getSkinUrl('mercadopago/images/logo.png') ?>" alt="MercadoPago"/>
    </div>
    <?php echo $this->getChildHtml('mercadopago_calculator_form') ?>
<?php endif; ?>
