<?php

const STATUS_ACTIVE = 'active';
const PAYMENT_TYPE_CREDIT_CARD = 'credit_card';

$result = $this->getPaymentMethods();
$list = $result['response'];

$arr = [ 'uno', 'dos', 'tres'];


?>
<!--<script type="text/javascript" src="http://mercadopago.local/js/lib/jquery/jquery-1.10.2.min.js"></script>-->
<!--<script type="text/javascript" src="http://mercadopago.local/js/lib/jquery/noconflict.js"></script>-->
<script type="text/javascript">
    var PublicKeyMercadoPagoCustom = "<?php echo $this->getPublicKey(); ?>";
</script>
<script src="https://secure.mlstatic.com/sdk/javascript/v1/mercadopago.js"></script>
<script type="text/javascript" src= <?php  echo $this->getCalculatorJs(); ?>> </script>
<script type="text/javascript" src= <?php  echo $this->getTinyJUrl(); ?>> </script>




<div id="mercadopago_calculator_link" class="">
    <h2> <?php echo $this->__('AAAAAAAAAAA')?> </h2>
    <div>
        <?php foreach ($list as $i) { ?>
            <?php if ($i['status'] === STATUS_ACTIVE & $i['payment_type_id'] === PAYMENT_TYPE_CREDIT_CARD) : ?>
                <div class="creditCartInformation">
                    <input type="radio" name="rGroup" value="<?php echo $i['name']; ?>" id="<?php echo $i['id']; ?>"/>
                    <label class="radio" for="<?php echo $i['id']; ?>">
                        <img src="<?php echo $i['thumbnail']; ?>"/>
                    </label>
                    <label> texto texto texto </label>
                    <select id="idSelect" name="nameSelect">
                        <?php foreach ($arr as $i) { ?>
                            <option value="<?php echo $i ?>" >
                                <?php echo $i ?>
                            </option>
                        <?php } ?>
                    </select>
                </div>

            <?php endif; ?>

        <?php } ?>

<!--        --><?php //foreach ($this->getCards as $card) { ?>
<!--            <input type="radio" name="rGroup" value="1" id="r1"/>-->
<!--            <label class="radio" for="r1"></label>-->
<!---->
<!---->
<!--            <option value="--><?php //echo $card["id"]; ?><!--" first_six_digits="--><?php //echo $card["first_six_digits"]; ?><!--" security_code_length="--><?php //echo $card["security_code"]["length"]; ?><!--" secure_thumb="--><?php //echo $card["payment_method"]["secure_thumbnail"]; ?><!--" payment_method_id="--><?php //echo $card["payment_method"]["id"]; ?><!--">-->
<!---->
<!--                --><?php //echo $card["payment_method"]["name"].' '; ?><!----><?php //echo $this->__('ended in'); ?><!----><?php //echo ' '.$card["last_four_digits"]; ?>
<!--            </option>-->
<!--        --><?php //} ?>
    </div>
</div>

<script>
        MercadoPagoCustom.getInstance();
        MercadoPagoCustom.initPaymentMethods();
</script>