<?php

/** * * NOTICE OF LICENSE * * This source file is subject to the Open Software License (OSL). 
 *  It is also available through the world-wide-web at this URL: *
 *  http://opensource.org/licenses/osl-3.0.php * 
 *  @category    Payment Gateway * @package    	MercadoPago 
 *  @author      André Fuhrman (andrefuhrman@gmail.com) 
 *  @copyright  Copyright (c) MercadoPago [http://www.mercadopago.com] 
 *  @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0) 
 */
?>


<?php 

if ($this->getAllowed() == 1){
if ($this->getCountry() == 'MLB'){?>
<img id="mpbttop" class="mpboton" src="<?php echo $this->getimgcheckoutBr()  ;?>" alt="<?php echo $this->__('Comprar Agora com MercadoPago');?>" title="<?php echo $this->__('Faça o pagamento de forma rápida e segura pelo MercadoPago');?>" style="cursor:pointer;" />
<span style="line-height:3.3; padding-left:2px;padding-right:2px;"><b><?php echo $this->__('Ou');?></b></span>
<?php }else{ ?>
<img id="mpbttop" class="mpboton" src="<?php echo $this->getimgcheckoutAr()  ;?>" alt="<?php echo $this->__('Compre  Ahora con MercadoPago');?>" title="<?php echo $this->__('Hace pagos de forma rápida y segura con MercadoPago');?>" style="cursor:pointer;" />
<span style="line-height:3.3; padding-left:2px;padding-right:2px;"><b><?php echo $this->__('O');?></b></span>    
<?php };?>
<?php } ;?>



