<?php

/** * * NOTICE OF LICENSE * * This source file is subject to the Open Software License (OSL). 
 *  It is also available through the world-wide-web at this URL: *
 *  http://opensource.org/licenses/osl-3.0.php * 
 *  @category    Payment Gateway * @package    	MercadoPago 
 *  @author      André Fuhrman (andrefuhrman@gmail.com) 
 *  @copyright  Copyright (c) MercadoPago [http://www.mercadopago.com] 
 *  @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0) 
 */
?>


<?php if ($this->getAllowedProduct() == 1){?>
<div class="mercadopagoaddcart">
<?php
if ($this->getCountry() == 'MLB'){?>
<span style="line-height:3.3; padding-left:2px;padding-right:2px;"><b><?php echo $this->__('Ou');?></b></span>    
<img id="mpadd" class="mpboton" src="<?php echo $this->getimgcheckoutBr()  ;?>" alt="<?php echo $this->__('Comprar Agora com MercadoPago');?>" title="<?php echo $this->__('Compre esse produto agora de forma rápida e segura com MercadoPago');?>" style="cursor:pointer;" />
<?php }else{ ?>
<span style="line-height:3.3; padding-left:2px;padding-right:2px;"><b><?php echo $this->__('O');?></b></span> 
<img id="mpadd" class="mpboton" src="<?php echo $this->getimgcheckoutAr()  ;?>" alt="<?php echo $this->__('Compre  Ahora con MercadoPago');?>" title="<?php echo $this->__('Compre eso produto de forma rápida y segura con MercadoPago');?>" style="cursor:pointer;" />
<?php };?>
</div>
<?php } ;?>

<input type="hidden" id="mpurl" name="return_url" value="" />

<script type="text/javascript">
    
    
    
//<![CDATA[

                
               
            
          
//]]>
</script>





