<?php

/**
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL).
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   	Payment Gateway
 * @package    	MercadoPago
 * @author      André Fuhrman (andrefuhrman@gmail.com)
 * @copyright  	Copyright (c) MercadoPago [http://www.mercadopago.com]
 * @license    	http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

?>

<fieldset class="form-list">
    <?php  $_code=$this->getMethodCode(); ?>
    <?php $_country = $this->getMethodCountry(); ?>

<ul id="payment_form_<?php  echo $_code ?>" >
       
        <?php if($this->getMethod()->getConfigData('acc_origin') == 'MLB'): ?>    
       <li>
       <img src="<?php echo $this->getSkinUrl('images/mpexpress/mercadopagobr.jpg'); ?>" alt="MercadoPago" title="MercadoPago" />
       </li>
       <li>
       <?php echo $this->__('O Pagamento será realizado em uma janela de segurança do MercadoPago') ?>
       </li>
       <?php elseif($this->getMethod()->getConfigData('acc_origin') == 'MLM'): ?>  
       <li>
       <img src="<?php echo $this->getSkinUrl('images/mpexpress/mercadopagomx.jpg'); ?>" alt="MercadoPago" title="MercadoPago" />
       </li>
       <li>
       <?php echo $this->__('El pago se realizará en una ventana de seguridad de MercadoPago') ?>
       </li>
       <?php elseif($this->getMethod()->getConfigData('acc_origin') == 'MLV'): ?>  
       <li>
       <img src="<?php echo $this->getSkinUrl('images/mpexpress/mercadopagove.jpg'); ?>" alt="MercadoPago" title="MercadoPago" />
       </li>
       <li>
       <?php echo $this->__('El pago se realizará en una ventana de seguridad de MercadoPago') ?>
       </li>
       <?php else: ?>  
       <li>
       <img src="<?php echo $this->getSkinUrl('images/mpexpress/mercadopagoar.jpg'); ?>" alt="MercadoPago" title="MercadoPago" />
       </li>
       <li>
       <?php echo $this->__('El pago se realizará en una ventana de seguridad de MercadoPago') ?>
       </li>
      <?php endif; ?> 
       
</ul>
<div>
    <?php echo $this->getMethod()->getConfigData('message');?>
</div>





